name: Workflow for Juan
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: example of multi-line commands
        run: |
            echo "Hello, Juan!"
            echo "Bye-bye, now!"
