name: Workflow for Juan
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello, Juan!"
      - name: print goodbye
        run: echo "Bye-bye, now!"
    
